//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionNotasCunor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alumno()
        {
            this.asign_alumno = new HashSet<asign_alumno>();
            this.calificacion = new HashSet<calificacion>();
        }
    
        public int id_alumno { get; set; }

        [Required(ErrorMessage = "El Carnet es requerido")]
        public string carnet { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        public string nombres { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        public string apellidos { get; set; }

        public int id_sexo { get; set; }

        public string telefono { get; set; }

        [EmailAddress(ErrorMessage = "El email no tiene el formato correcto")]
        public string email { get; set; }

    
        public virtual sexo sexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asign_alumno> asign_alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calificacion> calificacion { get; set; }
    }
}
