//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionNotasCunor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asign_alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asign_alumno()
        {
            this.detalle_asign = new HashSet<detalle_asign>();
        }
    
        public int id_asign_alumno { get; set; }
        public int id_alumno { get; set; }
        public int ciclo { get; set; }
        public int anio { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_carrera { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual carrera carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_asign> detalle_asign { get; set; }
    }
}
