//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionNotasCunor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class asign_curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asign_curso()
        {
            this.actividad = new HashSet<actividad>();
            this.detalle_asign = new HashSet<detalle_asign>();
        }
        
        [Required(ErrorMessage ="Este campo es requerido")]
        public int id_carrera { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        public int id_curso { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        public string seccion { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        public int id_catedratico { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        public string salon { get; set; }
        public int id_asign_curso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividad> actividad { get; set; }
        public virtual carrera carrera { get; set; }
        public virtual catedratico catedratico { get; set; }
        public virtual curso curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_asign> detalle_asign { get; set; }
    }
}
