//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionNotasCunor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catedratico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catedratico()
        {
            this.asign_curso = new HashSet<asign_curso>();
        }
    
        public int id_catedratico { get; set; }
        public string colegiado { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public int id_sexo { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string profesion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asign_curso> asign_curso { get; set; }
        public virtual sexo sexo { get; set; }
    }
}
