//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionNotasCunor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ctxNotasCunor : DbContext
    {
        public ctxNotasCunor()
            : base("name=ctxNotasCunor")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividad> actividad { get; set; }
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<asign_alumno> asign_alumno { get; set; }
        public virtual DbSet<asign_curso> asign_curso { get; set; }
        public virtual DbSet<caracteristica> caracteristica { get; set; }
        public virtual DbSet<carrera> carrera { get; set; }
        public virtual DbSet<catedratico> catedratico { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<detalle_asign> detalle_asign { get; set; }
        public virtual DbSet<sexo> sexo { get; set; }
        public virtual DbSet<calificacion> calificacion { get; set; }
    }
}
